<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>BenjaminMenu.Wave7.Fix4.CompletePreset</AssemblyName>
    <RootNamespace>BenjaminMenu.Wave7Fix4</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>1.5.0</Version>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="HarmonyX" Version="2.9.0" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" PrivateAssets="all" />
  </ItemGroup>
</Project>
